title: Edited password
id: 48528e1b-ae00-46b8-8bd9-cc15a77b4dbb
description: Détection de toute modification de mots de passe sur le système
status: experimental
tags:
  - attack.credential_access
  - attack.t1098 
logsource:
  product: linux
  service: auth
detection:
  selection:
      message|contains:
          - "passwd: password updated"
          - "passwd: password changed"
  condition: selection
falsepositives:
  - Modification légitime du mot de passe par un administrateur système autorisé
level: high