title: SSH Off Hours Detection
id : 970700d8-17ef-4552-8553-5a5539113370
description: Détection de toute connexion SSH qui a lieu hors horaires de bureaux classiques
status: experimental
tags:
  - attack.persistence
  - attack.t1078
logsource:
  product: linux
  service: ssh
detection:
  selection:
      message|contains:
          - "Accepted password"
          - "Accepted publickey"
  condition: selection
falsepositives:
  - Intervention d'urgence planifiée
level: medium