title: SSH Brute Force Detection
id : fe55c29d-c193-4e44-93a5-5f6b68ae2ae0
description: Détection de tentatives de connexions SSH par bruteforce
status: experimental
tags :
  - attack.credential_access
  - attack.t1110.001   
logsource:
  product: linux
  service: ssh
detection:
  selection:
    message:
      - "Failed password for"
      - "Invalid user"
  condition: selection #| count(user.name) by source.ip > 5
falsepositives:
  - "Tentatives de connexion légitimes par des utilisateurs autorisés (oubli de mot de passe, erreur de saisie.)"
level: high
