title: Sensitive File Access Detection
id : 6b47333d-1147-4056-8d16-cd0cdd00a4a5
description: Détection de tentatives d'accès à des fichiers sensibles
status: experimental
tags:
  - attack.credential_access
  - attack.t1552.001
logsource:
  product: linux
  service: syslog
detection:
  selection_file:
      message|contains:
          - "/etc/shadow"
          - "/etc/passwd"
          - "/etc/sudoers"
          - "/etc/ssh/"
          - "/etc/ssl/"
          - "/etc/mysql/"
          - "/etc/apache2/"
          - "/etc/httpd/"
          - "/etc/nginx/"
          - ".ssh/authorized_keys"
  condition: selection_file
falsepositives:
  - Accès légitime à des fichiers sensibles par un administrateur système autorisé
level: Critical