title: Pass The Hash
id: 3b4c5d6e-7f80-9012-cdef-012345678901
description: Détection d'une tentative de Pass-the-Hash via authentification NTLM suspecte
status: experimental
tags:
    - attack.lateral_movement
    - attack.t1550.002
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4624        # Connexion réussie
        LogonType: 3         # Connexion réseau
        AuthenticationPackageName: 'NTLM' # Authentification NTLM suspecte
    filter:
        TargetUserName|endswith: '$'
    condition: selection and not filter
falsepositives:
    - Authentification NTLM légitime sur le réseau
level: critical
