description: Détection de toute modification de mots de passe sur le système
filter:
- query:
    query_string:
      query: message:(*passwd\:\ password\ updated* OR *passwd\:\ password\ changed*)
name: Edited password
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
