description: Détection de toute création de nouvel utilisateur sur le système
filter:
- query:
    query_string:
      query: message:(*useradd\:\ new\ user* OR *new\ user\ added* OR *adduser*)
name: new user created
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
