# MITRE ATT&CK: T1548.003 (Privilege Escalation)
description: Détection de toute utilisation sudo suspecte
filter:
- query:
    query_string:
      query: message:(*sudo\:\ authentication\ failure* OR *sudo\:\ unable\ to\ resolve\
        host* OR *user\ NOT\ in\ sudoers* OR *COMMAND\=\/bin\/bash* OR *COMMAND\=\/bin\/sh*)
name: Suspicious Sudo usage
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
