# MITRE ATT&CK: T1110.001 (Credential Access)
description: Détection de tentatives de connexions SSH par bruteforce
filter:
- query:
    query_string:
      query: message:(Failed\ password\ for OR Invalid\ user)
name: SSH Brute Force Detection
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
