# MITRE ATT&CK: T1548.003 (Privilege Escalation)
description: Détection de toute modification des sudoers sur le système
filter:
- query:
    query_string:
      query: message:(*\/etc\/sudoers* OR *sudo\:\ \/etc\/sudoers.d\/user\:\ parsed\
        OK* OR *usermod\:\ adding\ user\ to\ group\ sudo*)
name: Sudoers modification
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
