description: Scan de ports détecté sur le réseau
filter:
- query:
    query_string:
      query: message:(*DROPPED* OR *iptables* OR *Firewall.*Blocked* OR *TCP_IN\ Blocked*)
index: con4mity-logs-*
name: Port scan detection
priority: 2
type: any
timestamp_field: '@timestamp'
alert:
- post
http_post_url: http://__DASHBOARD__/api/webhook/alert
http_post_headers:
  X-Webhook-Token: __TOKEN__
  Content-Type: application/json
http_post_static_payload:
  rule_name: Port scan detection
  severity: medium
http_post_payload:
  host: host
realert:
  minutes: 1
