# MITRE ATT&CK: T1021.004 + T1078 (Lateral Movement)
description: Détection de tentatives de connexions SSH Root (échouées et réussies)
filter:
- query:
    query_string:
      query: message:(*Failed\ password\ for\ root* OR *Accepted\ password\ for\ root*
        OR *Accepted\ publickey\ for\ root*)
name: SSH Root Login Detection
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
