# MITRE ATT&CK: T1078 (Defense Evasion)
description: Détection de toute connexion SSH qui a lieu hors horaires de bureaux
  classiques
filter:
- query:
    query_string:
      query: message:(*Accepted\ password* OR *Accepted\ publickey*)
name: SSH Off Hours Detection
priority: 2
type: any
severity: medium
index: con4mity-logs-*
alert:
- post
