# MITRE ATT&CK: T1046 (Discovery)
description: Scan de ports détecté sur le réseau
filter:
- query:
    query_string:
      query: message:(*DROPPED* OR *iptables* OR *Firewall.*Blocked* OR *TCP_IN\ Blocked*)
name: Port scan detection
priority: 2
type: any
severity: medium
index: con4mity-logs-*
alert:
- post
