# MITRE ATT&CK: T1136.002 (Persistence)
description: Détection de la création d'un nouveau compte administrateur dans l'Active
  Directory
filter:
- query:
    query_string:
      query: EventID:4720 AND (EventID:4732 AND (GroupName:(*Administrators* OR *Domain\
        Admins*)))
name: New Admin Account Created in AD
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
