description: 'Detection de la création d''une nouvelletâche planifiée qui pointe vers
  un emplacement suspect (ex : dossier temporaire, dossier utilisateur)'
filter:
- query:
    query_string:
      query: EventID:4698 AND (TaskContent:(*C\:\\Temp\\* OR *C\:\\Users\\* OR *C\:\\ProgramData\\*
        OR *%TEMP%* OR *%APPDATA%*))
name: New Scheduled Task Created
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
