# MITRE ATT&CK: T1562.001 (Defense Evasion)
description: 'Détection de la désactivation manuelle de Windows Defender par un utilisateur
  ou processus (ex : installation d''un logiciel malveillant sans connaissance de
  l''utilisateur)'
filter:
- query:
    query_string:
      query: EventID:5001
name: Windows Defender Disabled
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
