description: Détection de connexions RDP successives échouées
filter:
- query:
    query_string:
      query: EventID:4625 AND LogonType:10
name: RDP brute force detection
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
