description: 'Détection de la désactivation manuelle de Windows Defender par un utilisateur
  ou processus (ex : installation d''un logiciel malveillant sans connaissance de
  l''utilisateur)'
filter:
- query:
    query_string:
      query: EventID:5001
index: con4mity-logs-*
name: Windows Defender Disabled
priority: 4
type: any
timestamp_field: '@timestamp'
alert:
- post
http_post_url: http://__DASHBOARD__/api/webhook/alert
http_post_headers:
  X-Webhook-Token: __TOKEN__
  Content-Type: application/json
http_post_static_payload:
  rule_name: Windows Defender Disabled
  severity: critical
http_post_payload:
  host: host
realert:
  minutes: 1
