description: Détection de connexions (réseau ou rdp) réussies après plusieurs échecs
  de connexion
filter:
- query:
    query_string:
      query: (EventID:4625 AND (LogonType:(3 OR 10))) AND (EventID:4624 AND (LogonType:(3
        OR 10)))
name: Login after failures
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
