description: Détection de connexion suspecte avec un compte local désactivé
filter:
- query:
    query_string:
      query: EventID:4625 AND SubStatus:0xC0000072
name: Connection with disabled account
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
