# MITRE ATT&CK: T1562.004 (Defense Evasion)
description: Détection de la désactivation du pare-feu Windows
filter:
- query:
    query_string:
      query: EventID:(2002 OR 2083 OR 2003 OR 2082 OR 2008)
name: Firewall Disabled and/or Rules Deleted
priority: 2
type: any
severity: medium
index: con4mity-logs-*
alert:
- post
