description: Détection de verrouillage de compte utilisateur
filter:
- query:
    query_string:
      query: EventID:4740
name: Account Lockout
priority: 2
type: any
severity: medium
index: con4mity-logs-*
alert:
- post
