# MITRE ATT&CK: T1200 (Initial Access)
description: Detection de l'insertion d'un périphérique USB
filter:
- query:
    query_string:
      query: EventID:6416 AND (ClassName:(*DiskDrive* OR *USB\ Mass\ Storage*))
name: USB Device Connected
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
