# MITRE ATT&CK: T1021 (Lateral Movement)
description: Détection de mouvement latéral via connexion réseau suspecte entre machines
filter:
- query:
    query_string:
      query: EventID:4624 AND LogonType:3 AND TargetUserName:*$
name: Lateral Movement Detection
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
