description: Détection de modification d'un groupe à privilèges dans l'AD
filter:
- query:
    query_string:
      query: (EventID:(4728 OR 4732 OR 4756)) AND (GroupName:(*Domain\ Admins* OR
        *Enterprise\ Admins* OR *Schema\ Admins* OR *Administrators*))
name: Privilege Group Modified
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
