description: Détection de toute création de nouvel utilisateur local sur le système
filter:
- query:
    query_string:
      query: EventID:4720
name: New local user added
priority: 2
type: any
severity: medium
index: con4mity-logs-*
alert:
- post
