description: Détection de toute utilisation suspecte de Powershell (exécution de script,
  encodage, etc.)
filter:
- query:
    query_string:
      query: EventID:4104 AND (ScriptBlockText:(*\-EncodedCommand* OR *\-WindowStyle\
        Hidden* OR *IEX* OR *Invoke\-Expression* OR *DownloadString* OR *bypass* OR
        *FromBase64String* OR *.ps1* OR *Start\-Process* OR *Invoke\-Command*))
name: Suspicious Powershell usage
priority: 4
type: any
severity: critical
index: con4mity-logs-*
alert:
- post
