description: Détection de modification d'une stratégie de groupe (GPO)
filter:
- query:
    query_string:
      query: (EventID:(5136 OR 5137 OR 5141)) AND ObjectClass:groupPolicyContainer
name: GPO Modified
priority: 3
type: any
severity: high
index: con4mity-logs-*
alert:
- post
