services:
  fluentbit:
    image: fluent/fluent-bit:latest
    user: root
    environment:
      - FLB_HOSTNAME=kylian-collector
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /var/log:/var/log:ro
      - /tmp:/tmp
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf -R /fluent-bit/etc/parsers.conf
    ports:
      - "2020:2020"
    restart: unless-stopped
